In [10]:
import torch

In [ ]:
from qailab.circuit import build_circuit, RotationalEncoder, CXEntangler, RealAmplitudesBlock

input_encoder = RotationalEncoder('x','input')
quantum_circuit = build_circuit(
    3,
    [
        input_encoder,
        CXEntangler(),
        RealAmplitudesBlock('weight'),
        input_encoder, #You can put the same block twice in different parts of the circuit. It will encode the same parameters
        CXEntangler(),
        RealAmplitudesBlock('weight')
    ],
    measure_qubits=[0,1]
    )

In [ ]:
class QuantumAttention(nn.Module):
    def __init__(self):
        super(QuantumAttention, self).__init__()
        self.input_encoder = RotationalEncoder('x','input')
        self.qnn_circuit = build_circuit(
            3,
            [
                self.input_encoder,
                RealAmplitudesBlock('weight'),
                self.input_encoder, # You can put the same block twice in different parts of the circuit. It will encode the same parameters
            ],
            measure_qubits=[0,1,2] # Measure all qubits
            )

    def forward(self, x):
        

In [8]:
import torch.nn as nn
# from qailab.torch import QLayer

# qlayer = QLayer(
#     quantum_circuit,
#     shots = 2048
#     )

# sequential_net = nn.Sequential(
#     nn.Linear(4,qlayer.in_features),
#     nn.ReLU(),
#     qlayer,
#     nn.Linear(qlayer.out_features,4),
#     nn.Softmax()
# )

In [ ]:
import numpy as np
# QNN library integrating with PyTorch
from qailab.circuit import build_circuit, RotationalEncoder, RealAmplitudesBlock
from qailab.circuit.utils import assign_input_weight

input_encoder = RotationalEncoder('x','input')
qnn_circuit = build_circuit(
    3,
    [
        input_encoder,
        RealAmplitudesBlock('weight'),
        input_encoder, # You can put the same block twice in different parts of the circuit. It will encode the same parameters
    ],
    measure_qubits=[0,1,2] # Measure all qubits
    )

qnn_circuit.assign_parameters(assign_input_weight(qnn_circuit,[1,2,3],np.random.randint(0,9,12))).draw('mpl')

In [56]:
from qailab.torch import QLayer,QModel,orca_layer

qlayer = orca_layer.ORCALayer(3)

In [ ]:
myParameters = torch.tensor([[5.8932],
         [3.9148],
         [1.7986],
         [4.9899],
         [3.6941],
         [4.2348],
         [2.7410],
         [5.4953],
         [3.0173],
         [4.3170],
         [2.2644],
                             [1.1860]])

In [ ]:
myParameters

In [553]:
from QuantumSelfAttentionLayer import QuantumSelfAttentionLayer

In [565]:
qlayer = QuantumSelfAttentionLayer(100, 4, 5)

In [566]:
for p in qlayer.parameters():
    print(p)

Parameter containing:
tensor([[-2.1227e-01, -8.9329e-03,  1.1817e-01, -8.4667e-02,  6.8146e-02,
         -3.9404e-01],
        [ 1.3474e-01,  2.5167e-01,  2.8205e-01, -3.5767e-01,  2.5497e-01,
         -1.8302e-02],
        [-3.6671e-01, -1.5116e-04,  2.0924e-01, -3.9760e-01,  2.9678e-01,
         -2.7937e-02],
        [-4.4876e-02, -1.1559e-01, -1.2271e-01,  4.0002e-01, -5.9956e-03,
         -6.8764e-03]], requires_grad=True)
Parameter containing:
tensor([-0.3266,  0.2892,  0.0421,  0.0387], requires_grad=True)
Parameter containing:
tensor([[-0.1544, -0.1220, -0.3578,  0.2040,  0.3957,  0.1728],
        [-0.0359,  0.0718, -0.3407, -0.0406, -0.3325,  0.2524],
        [ 0.3298, -0.3969,  0.3754,  0.3771,  0.2182,  0.0167],
        [-0.3879, -0.1830,  0.0296,  0.2537,  0.2221, -0.2555]],
       requires_grad=True)
Parameter containing:
tensor([0.1610, 0.1588, 0.0054, 0.3238], requires_grad=True)
Parameter containing:
tensor([[ 0.1667,  0.1307,  0.2567, -0.2578, -0.1818,  0.1253],
       

In [567]:
[p for p in qlayer.parameters()]

[Parameter containing:
 tensor([[-2.1227e-01, -8.9329e-03,  1.1817e-01, -8.4667e-02,  6.8146e-02,
          -3.9404e-01],
         [ 1.3474e-01,  2.5167e-01,  2.8205e-01, -3.5767e-01,  2.5497e-01,
          -1.8302e-02],
         [-3.6671e-01, -1.5116e-04,  2.0924e-01, -3.9760e-01,  2.9678e-01,
          -2.7937e-02],
         [-4.4876e-02, -1.1559e-01, -1.2271e-01,  4.0002e-01, -5.9956e-03,
          -6.8764e-03]], requires_grad=True),
 Parameter containing:
 tensor([-0.3266,  0.2892,  0.0421,  0.0387], requires_grad=True),
 Parameter containing:
 tensor([[-0.1544, -0.1220, -0.3578,  0.2040,  0.3957,  0.1728],
         [-0.0359,  0.0718, -0.3407, -0.0406, -0.3325,  0.2524],
         [ 0.3298, -0.3969,  0.3754,  0.3771,  0.2182,  0.0167],
         [-0.3879, -0.1830,  0.0296,  0.2537,  0.2221, -0.2555]],
        requires_grad=True),
 Parameter containing:
 tensor([0.1610, 0.1588, 0.0054, 0.3238], requires_grad=True),
 Parameter containing:
 tensor([[ 0.1667,  0.1307,  0.2567, -0.2578, -

In [568]:
param_grads = torch.stack([p.grad for p in qlayer.parameters()])
print(param_grads)


TypeError: expected Tensor as element 0 in argument 0, but got NoneType

In [569]:
out = qlayer(torch.tensor([[1.0, 2.0, 1.0, 0.0, 0.1, 0.2]]))

In [570]:
out

tensor([[ 0.0705,  0.0567, -0.3282,  0.4262, -0.2790]], grad_fn=<MulBackward0>)

In [ ]:
loss_fn = torch.nn.MSELoss()

In [ ]:
loss = loss_fn(out, torch.tensor([0.1299, 0.7953, 0.0088, 0.0078, 0.1670, 0.0000, 0.4814, 0.0098]))

In [ ]:
loss

In [ ]:
loss.backward()

In [ ]:
out.grad

In [147]:
test = orca_layer.ORCALayer(
            in_features=2,
            n_loops=2,
            observable='avg-photons',
            gradient_mode='parameter-shift',
            n_samples=100,
            
        )

In [148]:
test

ORCALayer(
  (pt_layer): PTLayer(in_features=2, output_observables=3, trainable_theta=2)
)

In [137]:
loss = test.forward(torch.tensor([[0,1]]))

In [139]:
loss

tensor([[0.2700, 0.3487, 0.3812]], grad_fn=<TBIAutogradBackward>)

In [ ]:
class SelfAttentionLayer(nn.Module):
    def __init__(self, classical_input_size, classical_hidden_size, orca_in_features):
        super(HybridNetwork, self).__init__()
        
        # Classical feature extraction network
        self.feature_extractor = nn.Sequential(
            nn.Linear(classical_input_size, classical_hidden_size),
            nn.ReLU()
        )
        
        # Network to generate ORCA input data
        self.orca_input_generator = nn.Linear(classical_hidden_size, orca_in_features)
        
        # Network to generate ORCA parameters (thetas)
        self.orca_param_generator = nn.Linear(classical_hidden_size, orca_in_features)
        
        # ORCA quantum layer
        self.orca_layer = orca_layer.ORCALayer(
            in_features=orca_in_features,
            observable='avg-photons',
            gradient_mode='parameter-shift',
            n_samples=100,
            n_loops=2,
        )
    
    def forward(self, query, key):
        # Extract features from input
        features = self.feature_extractor(query)
        print(features.shape)
        # Generate ORCA input data
        orca_inputs = self.orca_input_generator(features)
        print(orca_inputs.shape)
        # Generate dynamic parameters for ORCA layer
        theta_params = self.orca_param_generator(features)
        print(theta_params.shape)
        # Update ORCA parameters
        self.orca_layer.set_thetas(key)
        print(theta_params.shape)
        # Process through quantum layer
        quantum_output = self.orca_layer(orca_inputs)
        print(quantum_output.shape)
        
        return quantum_output

In [394]:
class HybridNetwork(nn.Module):
    def __init__(self, classical_input_size, classical_hidden_size, orca_in_features):
        super(HybridNetwork, self).__init__()
        
        # Classical feature extraction network
        self.feature_extractor = nn.Sequential(
            nn.Linear(classical_input_size, classical_hidden_size),
            nn.ReLU()
        )
        
        # Network to generate ORCA input data
        self.orca_input_generator = nn.Linear(classical_hidden_size, orca_in_features)
        
        # ORCA quantum layer
        self.orca_layer = orca_layer.ORCALayer(
            in_features=orca_in_features,
            observable='avg-photons',
            gradient_mode='parameter-shift',
            n_samples=100,
            n_loops=2,
        )
        
        # Initialize a parameter buffer to store original key gradients
        self.register_buffer('orig_key', None)
        self.key_requires_grad = False
    
    def forward(self, query, key):
        # Save the original key tensor and its requires_grad state
        self.orig_key = key
        self.key_requires_grad = key.requires_grad
        
        # Extract features from input
        features = self.feature_extractor(query)
        
        # Generate ORCA input data
        orca_inputs = self.orca_input_generator(features)
        
        # Update ORCA parameters with the key
        self.orca_layer.set_thetas(key)
        
        # Register a hook for backward to capture gradients
        if self.key_requires_grad:
            # Get the parameter that was set in the ORCA layer
            for param in self.orca_layer.parameters():
                if param.shape == key.shape:
                    param.register_hook(lambda grad: self._save_grad_to_key(grad))
        
        # Process through quantum layer
        quantum_output = self.orca_layer(orca_inputs)
        
        return quantum_output
    
    def _save_grad_to_key(self, grad):
        # This function will be called during backward pass
        # It passes the gradient from the ORCA parameters back to the original key
        if self.orig_key.grad is None:
            self.orig_key.grad = grad.clone()
        else:
            self.orig_key.grad += grad.clone()
        return grad

In [546]:
class QuantumAttention(nn.Module):
    def __init__(self, classical_input_size, orca_in_features, orca_out_features):
        super(QuantumAttention, self).__init__()
        

        self.keyMatrix = nn.Linear(classical_input_size, orca_in_features)
        self.queryMatrix = nn.Linear(classical_input_size, orca_in_features)
        self.valueMatrix = nn.Linear(classical_input_size, orca_out_features) 

        
        
        # ORCA quantum layer
        self.orca_layer = orca_layer.ORCALayer(
            in_features=orca_in_features,
            observable='avg-photons',
            gradient_mode='parameter-shift',
            n_samples=100,
            n_loops=2,
        )
        
        # Initialize a parameter buffer to store original key gradients
        self.register_buffer('orig_query', None)
        self.query_requires_grad = False
    
    def forward(self, x):
        # Save the original key tensor and its requires_grad state
        key = self.keyMatrix(x)
        query = self.queryMatrix(x)
        value = self.valueMatrix(x)
        
        self.orig_query = query
        self.query_requires_grad = query.requires_grad
        
        # Update ORCA parameters with the key
        self.orca_layer.set_thetas(query)
        
        # Register a hook for backward to capture gradients
        if self.query_requires_grad:
            # Get the parameter that was set in the ORCA layer
            for param in self.orca_layer.parameters():
                if param.shape == query.shape:
                    param.register_hook(lambda grad: self._save_grad_to_query(grad))
        
        # Process through quantum layer
        key_querry = self.orca_layer(key)

        output = key_querry * value
        
        return output
    
    def _save_grad_to_query(self, grad):
        # This function will be called during backward pass
        # It passes the gradient from the ORCA parameters back to the original key
        if self.orig_query.grad is None:
            self.orig_query.grad = grad.clone()
        else:
            self.orig_query.grad += grad.clone()
        return grad

In [547]:
qlayer = QuantumAttention(4, 3, 4)

In [548]:
qlayer(torch.tensor([[0.1, 0.2, 0.3, 0.5]]))

tensor([[ 0.1177, -0.0432, -0.0091, -0.2074]], grad_fn=<MulBackward0>)

In [395]:
layer = HybridNetwork(4,4,3)

In [534]:
inp = torch.tensor([[0.1, 0.2, 0.3, 0.5]])
inp.requires_grad = True

In [535]:
inp

tensor([[0.1000, 0.2000, 0.3000, 0.5000]], requires_grad=True)

In [552]:
qlayer(inp)

tensor([[0.4844, 0.0979, 0.2054, 0.1000]], grad_fn=<MulBackward0>)

In [481]:
testik = torch.tensor([-0.2,0.2,0.2])
testik.requires_grad = True

In [549]:
optimizer = torch.optim.Adam(qlayer.parameters(), lr=0.001)

In [550]:
for i in range(10000):
    optimizer.zero_grad()
    out = qlayer(inp)
    loss = torch.mean((out-torch.tensor([0.5, 0.1, 0.2, 0.1]))**2)
    loss.backward()
    optimizer.step()
    if i%100 == 0:
        print(loss.item())

/tmp/ipykernel_23832/3348060093.py:54: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  if self.orig_query.grad is None:


0.07637156546115875
0.02252538688480854
0.0034922384656965733
0.0007740415167063475
0.00022456367150880396
5.3255422244546935e-05
2.0279419914004393e-05


Traceback (most recent call last):
  File "/home/maciej/miniconda3/envs/medi/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3667, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_23832/737111166.py", line 3, in <module>
    out = qlayer(inp)
          ^^^^^^^^^^^
  File "/home/maciej/miniconda3/envs/medi/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maciej/miniconda3/envs/medi/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ipykernel_23832/3348060093.py", line 45, in forward
    key_querry = self.orca_layer(key)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/maciej/miniconda3/envs/medi/lib/python3.12/site-packages/torch/nn/modules/module.py", line 

KeyboardInterrupt: 

In [475]:
for p in layer.orca_layer.parameters():
    print(p.grad)

tensor([ 0.1821, -0.0447, -0.0288])


In [476]:
inp

tensor([[1.2095, 0.1204, 0.4037, 0.4919]], grad_fn=<SubBackward0>)

In [477]:
testik.grad

tensor([ 1.2529, -0.5077, -0.7002])